using MemGuard.Core;
using Markdig;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace MemGuard.Reporters;

/// <summary>
/// Base class for report generators using template method pattern
/// </summary>
public abstract class ReportGeneratorBase : IReporter
{
    public abstract string Format { get; }
    
    public string GenerateReport(AnalysisResult result)
    {
        ArgumentNullException.ThrowIfNull(result);

        var header = GenerateHeader(result);
        var body = GenerateBody(result);
        var footer = GenerateFooter(result);
        
        return $"{header}\n{body}\n{footer}";
    }
    
    protected virtual string GenerateHeader(AnalysisResult result)
    {
        ArgumentNullException.ThrowIfNull(result);

        return $"# MemGuard Analysis Report\n\n**Confidence Score:** {result.ConfidenceScore:P2}\n\n---\n";
    }
    
    protected abstract string GenerateBody(AnalysisResult result);
    
    protected virtual string GenerateFooter(AnalysisResult result)
    {
        return $"\n---\n*Report generated by MemGuard AI Debugger*";
    }
}

/// <summary>
/// Generates Markdown reports
/// </summary>
public class MarkdownReporter : ReportGeneratorBase
{
    public override string Format => "markdown";
    
    protected override string GenerateBody(AnalysisResult result)
    {
        ArgumentNullException.ThrowIfNull(result);

        var markdown = $"## Root Cause\n\n{result.RootCause}\n\n";
        markdown += $"## Recommended Fix\n\n```diff\n{result.CodeFix}\n```\n\n";
        markdown += "## Diagnostic Details\n\n";
        
        foreach (var diagnostic in result.Diagnostics)
        {
            markdown += $"### {diagnostic.Type}\n\n";
            markdown += $"{diagnostic.Description}\n\n";
            markdown += $"**Severity:** {diagnostic.Severity}\n\n";
        }
        
        return markdown;
    }
}

/// <summary>
/// Generates HTML reports
/// </summary>
public class HtmlReporter : ReportGeneratorBase
{
    public override string Format => "html";
    
    protected override string GenerateHeader(AnalysisResult result)
    {
        ArgumentNullException.ThrowIfNull(result);

        return $"<!DOCTYPE html><html><head><title>MemGuard Analysis Report</title></head><body>";
    }
    
    protected override string GenerateBody(AnalysisResult result)
    {
        ArgumentNullException.ThrowIfNull(result);

        var html = $"<h2>Root Cause</h2><p>{result.RootCause}</p>";
        html += $"<h2>Recommended Fix</h2><pre><code>{result.CodeFix}</code></pre>";
        html += "<h2>Diagnostic Details</h2><ul>";
        
        foreach (var diagnostic in result.Diagnostics)
        {
            html += $"<li><strong>{diagnostic.Type}</strong>: {diagnostic.Description} (Severity: {diagnostic.Severity})</li>";
        }
        
        html += "</ul>";
        return html;
    }
    
    protected override string GenerateFooter(AnalysisResult result)
    {
        return $"<hr><p><em>Report generated by MemGuard AI Debugger</em></p></body></html>";
    }
}

/// <summary>
/// Generates PDF reports using QuestPDF
/// </summary>
public class PdfReporter : IReporter
{
    public string Format => "pdf";
    
    public string GenerateReport(AnalysisResult result)
    {
        ArgumentNullException.ThrowIfNull(result);

        // In a real implementation, this would generate a PDF file
        // For now, we'll return a string representation
        return $"PDF Report: Root Cause: {result.RootCause} | Code Fix: {result.CodeFix}";
    }
    
    /*
    // This would be the actual implementation:
    public byte[] GeneratePdfReport(AnalysisResult result)
    {
        return QuestPDF.Fluent.Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.PageColor(Colors.White);
                
                page.Header()
                    .Text("MemGuard Analysis Report")
                    .SemiBold().FontSize(16);
                
                page.Content()
                    .PaddingVertical(1, Unit.Centimetre)
                    .Column(x =>
                    {
                        x.Item().Text($"Root Cause: {result.RootCause}");
                        x.Item().Text($"Code Fix: {result.CodeFix}");
                        // Add more content...
                    });
                
                page.Footer()
                    .AlignCenter()
                    .Text($"Confidence Score: {result.ConfidenceScore:P2}");
            });
        })
        .GeneratePdf();
    }
    */
}